application: desertorest
version: 1
runtime: php55
api_version: 1
threadsafe: yes


handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(.+\.php)$
  script: \1

- url: /(.+\.(gif|png|jpg|html|css|js|ttf|mp4))$
  static_files: \1
  upload: .+\.(gif|png|jpg|html|css|js|ttf|mp4)$
  application_readable: true

- url: .*
  script: index.html
